# Generated by Django 3.2.13 on 2022-07-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.FloatField(null=True),
        ),
    ]
