# Generated by Django 3.2.13 on 2022-07-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartapp.cart'),
        ),
    ]
