# Generated by Django 3.2.13 on 2022-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cartprice',
            field=models.IntegerField(null=True),
        ),
    ]
