# Generated by Django 3.2.13 on 2022-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
