# Generated by Django 3.2.13 on 2022-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryies',
            name='offer',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
