# Generated by Django 3.2.13 on 2022-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0002_categoryies_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offerproduct',
            field=models.IntegerField(null=True),
        ),
    ]
