# Generated by Django 3.2.13 on 2022-07-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0003_auto_20220727_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryies',
            name='offer',
            field=models.IntegerField(null=True),
        ),
    ]
