# Generated by Django 3.2.13 on 2022-07-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0004_alter_categoryies_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='image1',
        ),
    ]
