# Generated by Django 3.2.13 on 2022-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0005_rename_image3_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryies',
            name='offerstatus',
            field=models.BooleanField(default=True),
        ),
    ]
