# Generated by Django 3.2.13 on 2022-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0006_categoryies_offerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerstatuspro',
            field=models.BooleanField(default=True),
        ),
    ]
