# Generated by Django 3.2.13 on 2022-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.CharField(max_length=2500, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
