# Generated by Django 3.2.13 on 2022-08-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
