# Generated by Django 3.2.13 on 2022-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
