# Generated by Django 3.2.13 on 2022-07-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theproducts', '0001_initial'),
        ('orders', '0002_auto_20220718_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='carts',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordertotal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='theproducts.product')),
            ],
        ),
    ]
