# Generated by Django 3.2.13 on 2022-07-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220719_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordertotal',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
