# Generated by Django 3.2.13 on 2022-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'WALLET'), ('COD', 'COD'), ('PAYPAL', 'PAYPAL'), ('RAZOR_PAY', 'RAZORPAY')], max_length=100),
        ),
    ]
