# Generated by Django 3.2.13 on 2022-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
